name: Deploy to VPS

on:
  push:
    branches:
      - main # oder dein Haupt-Branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Der Job läuft auf einem von GitHub bereitgestellten Runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }} # IP-Adresse deines Servers
        username: ${{ secrets.VPS_USERNAME }} # Dein Benutzername auf dem VPS
        key: ${{ secrets.VPS_SSH_KEY }} # Dein privater SSH-Key für den Server-Login
        script: |
          cd /var/www/tinyllm
          git pull origin main
          npm install
          npm run build # Für Next.js oder Astro
          pm2 restart meine-app # Starte die App mit PM2 neu