name: Deploy to VPS

on:
  push:
    branches:
      - main # oder dein Haupt-Branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Der Job läuft auf einem von GitHub bereitgestellten Runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Gehe ins Projektverzeichnis
          cd /var/www/tinyllm
      
          # Hole den neuesten Code
          git pull origin main
      
          # ------------------ LÖSUNG ------------------
          # Lade nvm und die korrekte Node.js-Umgebung
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          # ---------------------------------------------
          
          # Führe jetzt die Befehle aus
          npm install
          npm run build
          pm2 restart tinyllm